ports:
  - port: 3000
    onOpen: notify
  - port: 3100
    onOpen: ignore
  - port: 2000
    onOpen: ignore
tasks:
  - before: ./setup-bit.sh
    init: yarn && npx next build
    # init: yarn && ~/bin/bit import && ~/bin/bit link
    command: npm run dev
    # command: ~/bin/bit start
