const PRODUCTION_IC_PRODUCT_ID = 6592569704526
const PRODUCTION_TRENDING_COLLECTION_ID = 262384156750

const STAGING_IC_PRODUCT_ID = 6536762654810
const STAGING_TRENDING_COLLECTION_ID = 254551491

export const INNER_CIRCLE_PRODUCT_ID =
  process.env.APP_ENV === 'staging' ? STAGING_IC_PRODUCT_ID : PRODUCTION_IC_PRODUCT_ID
export const TRENDING_PRODUCTS_COLLECTION_ID =
  process.env.APP_ENV === 'staging' ? STAGING_TRENDING_COLLECTION_ID : PRODUCTION_TRENDING_COLLECTION_ID
